package me.avinas.tempo.data.diagnostics

/**
 * Everything a diagnostics report may be built from.
 *
 * Note what is deliberately **absent**: there is no field for a track title, artist name,
 * album, file path, account or device identifier. A report cannot leak listening content
 * because this type has nowhere to carry it — the same structural guarantee the analytics
 * schema relies on, rather than a rule someone has to remember.
 *
 * This report is never uploaded. It is generated on request and handed to the user to share
 * or discard, which is what makes it safe to include far more detail here than Tempo would
 * ever transmit on its own.
 */
data class DiagnosticsInput(
    val appVersion: String,
    val versionCode: Int,
    val androidApi: Int,
    val deviceModel: String,
    val databaseVersion: Int,
    val trackCount: Int,
    val artistCount: Int,
    val albumCount: Int,
    val eventCount: Int,
    val enrichmentCounts: Map<String, Int>,
    val notificationAccessGranted: Boolean,
    val listenerConnected: Boolean,
    val listenerAliveAgoMillis: Long?,
    val batteryOptimisationExempt: Boolean,
    val analyticsEnabled: Boolean,
    val analyticsDisclosureSeen: Boolean,
    val trackedAppCount: Int,
    val enabledAppCount: Int,
    val workerStates: Map<String, String>,
)

object DiagnosticsReport {
    fun build(input: DiagnosticsInput): String =
        buildString {
            appendLine("Tempo diagnostics report")
            appendLine("=".repeat(40))
            appendLine()
            appendLine("This report contains counts and status flags only. It has no track, artist or")
            appendLine("album names, no file paths and no account or device identifiers. Nothing was")
            appendLine("uploaded to produce it — review it and share it only if you choose to.")
            appendLine()

            appendLine("-- Build --")
            appendLine("App version      : ${input.appVersion} (${input.versionCode})")
            appendLine("Database version : ${input.databaseVersion}")
            appendLine("Android API      : ${input.androidApi}")
            appendLine("Device model     : ${input.deviceModel}")
            appendLine()

            appendLine("-- Library --")
            appendLine("Tracks           : ${input.trackCount}")
            appendLine("Artists          : ${input.artistCount}")
            appendLine("Albums           : ${input.albumCount}")
            appendLine("Listening events : ${input.eventCount}")
            appendLine()

            appendLine("-- Metadata enrichment --")
            if (input.enrichmentCounts.isEmpty()) {
                appendLine("No enrichment data recorded yet.")
            } else {
                input.enrichmentCounts.entries
                    .sortedBy { it.key }
                    .forEach { (status, count) -> appendLine("${status.padEnd(17)}: $count") }
            }
            appendLine()

            appendLine("-- Music detection health --")
            appendLine("Notification access   : ${input.notificationAccessGranted.yesNo()}")
            appendLine("Listener connected    : ${input.listenerConnected.yesNo()}")
            appendLine("Last heartbeat        : ${input.listenerAliveAgoMillis.describeAge()}")
            appendLine("Battery optimisation  : ${if (input.batteryOptimisationExempt) "exempt" else "NOT exempt"}")
            appendLine("Tracked apps          : ${input.trackedAppCount} (${input.enabledAppCount} enabled)")
            appendLine()

            appendLine("-- Anonymous app-health stats --")
            appendLine("Enabled          : ${input.analyticsEnabled.yesNo()}")
            appendLine("Notice seen      : ${input.analyticsDisclosureSeen.yesNo()}")
            appendLine()

            appendLine("-- Background work --")
            if (input.workerStates.isEmpty()) {
                appendLine("No scheduled work found.")
            } else {
                input.workerStates.entries
                    .sortedBy { it.key }
                    .forEach { (worker, state) -> appendLine("${worker.padEnd(22)}: $state") }
            }

            appendLine()
            appendLine("Report generated by Tempo. No listening content is included.")
        }

    private fun Boolean.yesNo(): String = if (this) "yes" else "no"

    private fun Long?.describeAge(): String {
        if (this == null || this < 0L) return "never"
        return when {
            this < 60_000L -> "just now"
            this < 60L * 60_000L -> "${this / 60_000L} min ago"
            this < 24L * 60L * 60_000L -> "${this / (60L * 60_000L)} h ago"
            else -> "${this / (24L * 60L * 60_000L)} d ago"
        }
    }
}
